### ISSUE TITLE
Google Photos - video keeps loading

### ISSUE THREAD

**Issue by bitpixl** [meh/smart-referer#100]
Hi,

I'm having problems playing (my) videos from https://photos.google.com.
The initial frame shows but it keeps loading.
I know for sure it's the referer because setting "network.http.referer.XOriginPolicy" to "0" fixed the issue.

Could you create a whitelist entry in the default list? I have no clue on how to manually create the whitelist rule.

thanks and keep up the great work!

**Comment by alexander255** [comment]
Thank you for reporting this issue!
Are you using both *Smart Referer* and `network.http.referer.XOriginPolicy` at the same time? Because `network.http.referer.XOriginPolicy` will always take precedence of whatever *Smart Referer* tries to, so this can not be supported unfortunately.
If this issue is still present with *Smart Referer* when you disable this setting (by setting it to `0`), you'll have provide some data for debugging it as I don't have access to your video – without this I cannot help you unfortunately. Please see [my comment on issue 69](https://github.com/meh/smart-referer/issues/69#issuecomment-342484721) for how to do this.

**Comment by bitpixl** [comment]
Hi Alexander, I did have "network.http.referer.XOriginPolicy" set to "1", so I set that to "0" while using your add-on. I checked out your post on issue 69 where you ask to use the network console. I found that using the browser console (ctrl+shift+j) gave me a very clear (better?) indication of what was causing the issue. What needs to be whitelisted is:

source: **photos.google.com** with destination: **youtube.googleapis.com**

After setting that manually in the exceptions the videos play as intented :+1:

**Comment by alexander255** [comment]
Don't close this yet; it's not fixed until it works for everybody (whitelist). :slightly_smiling_face:

**Comment by alexander255** [comment]
I combined the rule we had in place for `videos.google.com` from #33 with the one for this page (yielding `*.google.com>youtube.googleapis.com`) since other Google-internal sites are likely affected by this as well. Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now 🙂 

*Then* feel free to close this issue if it works now! :wink:
