### ISSUE TITLE
[Qestion] slip of the pen or special syntax?

### ISSUE THREAD

**Issue by DJCrashdummy** [meh/smart-referer#105]
shouldn't [line 45 concerning Sofortüberweisung.de of the default whitelist](https://github.com/meh/smart-referer/blob/gh-pages/whitelist.full.txt#L45) be rather `*.sofort.com>*.sofortueberweisung.de` than `*.sofort.com *.sofortueberweisung.de` without the `>`?

if not, can someone please explain this special syntax, since it is not seen at any other line...  
thanks for checking and/or explaining this!

**Comment by alexander255** [comment]
The syntax `*.sofort.com` is just a short form for `*>*.sofort.com`. It used to be common in the whitelist but got replaced by either the more elaborate, but also more obvious, syntax mentioned above or by a more restricted rule (some rules where also dropped when they didn't apply anymore).

See also [lines 26–32 of `background/policy.js`](https://github.com/meh/smart-referer/blob/ecf8887cbbba2cffb1c78e6a254acc5b58521070/background/policy.js#L26-L31).

I think I'll remove that line however since it it hasn't been verified in years… I'll probably also remove support for this syntax from the parser since it's non-obvious and only really used by that specific line anyways.

**Comment by DJCrashdummy** [comment]
@alexander255 thank you very much for your time and explaining this in detail!

i was guessing that it was a mistake, since 2 of this "short entries" (without a `>` but only separated by a ` `[space]) where side by side in one line...
