### ISSUE TITLE
Strict option doens't work anymore

### ISSUE THREAD

**Issue by ghost** [meh/smart-referer#18]
In all current Firefox versions (Firefox ESR to Nightly) the strict option doesn't work for me.
It does block referers from different domains but doesn't work on the same domain.
You can test this on `http://www.whatismyreferer.com/`, when you click the link to itself it gives the referer.

**Comment by alexander255** [comment]
The **Strict** option does work. You can test this by opening this page and clicking on the link: http://admin.xmine128.tk/ref-test.html

If you enable the **Strict** option the target page will tell you that your referer is `http://xmine128.tk/ref-test2.php`, without it the target page will show `http://admin.xmine128.tk/ref-test.html` instead (assuming default settings otherwise).

In your example you are navigating from the domain `www.whatismyreferer.com` to the domain `www.whatismyreferer.com`, so *Smart Referer* will NOT modify the referer. The **Strict** option would take effect only if you were navigating from, say, `whatismyreferer.com` to  `www.whatismyreferer.com` or vice versa.

Summary:
 * Same domain requests are never modified by *Smart Referer*
 * The **Strict** options only tells *Smart Referer* to "treat different subdomains as different domains"
 * Whenever *Smart Referer* considers the domain of the referer that would be sent different from the domain of the resource (page, image, ...) you are trying to load, then it will apply its rules.

I hope this clears things up!

Please comment on whether this makes sense to/works for you.

**Comment by alexander255** [comment]
Stale issue & OP removed their account in the mean time…
