### ISSUE TITLE
Fail to load selected TV program from HKTV

### ISSUE THREAD

**Issue by ReporterX** [meh/smart-referer#21]
You need to register a free account to reproduce the issue.

Go to http://www.hktvmall.com/hktv/en/main
Register and login
Play any selected TV program, for example http://snag.gy/rJWwy.jpg
Error occurs: "Connection unstable, please retry." (please ignore the message. It has nothing to do with unstable connection)

Note that it is ok to watch the live channel, but not when you select a particular TV program to play.
If you disable the addon, it can play successfully.
Putting the website into whitelist does not help.

**Comment by alexander255** [comment]
> Play any selected TV program
I just registered a free account but I'm not able to play anything since I don't know how to get there (I can't read this language).
Could you provide a direct-link to some broken TV program (or at least a step-by-step guide of how to get there)?

Sorry for being late!

**Comment by ReporterX** [comment]
Switch to English. It has an English interface.
There is no direct link available.
Just click on any TV program. It will load ads first. After the ad finishes, it will try to load the TV program but fails. Error: "Connection unstable, please retry."

![Fail to load on any TV program](http://snag.gy/wnEbm.jpg)

**Comment by alexander255** [comment]
Hi,
I've managed to get the video player working (sorry, the error was on my end), however all video content on hktvmall.com (even lame product videos) seems to be geolocked. :-(
![Screenshot](http://snag.gy/R05rp.jpg)

Since I don't have a proxy (and therefor won't be able to analyze this either way), let's just try this instead:

 1. Go to the video section of http://www.hktvmall.com/hktv/en/main
 2. Wait until the page done loading completely (i.e.: you see the **Connect unstable, please retry** message)
 3. Right click somewhere on the page and select **Inspect Element** from the menu
 4. A new browser panel show appear at the bottom of the page
 5. Select the **Network Monitor** tab in that new panel and ignore the message that says you should reload the page (1)
 6. Select a video that you haven't previously watched (2)
 7. Wait until you get the **Connect unstable, please retry** message
 8. Make sure you scroll to the bottom of the request list (3)
 9. Take a screenshot of the request list displayed

![Analysation strategy](http://snag.gy/qaCmf.jpg)

.

Meanwhile you may also try to use any of the following *Allow* rules in *Smart Referer*s addon settings to get this page to work (please try each of the separately and tell me the results):

 * hktvmall.com>*
 * d3btqb6knwd3a4.cloudfront.net>*
 * jwpcdn.net>*

Here is how you get to to *Smart Referer*s addon settings:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list

Even if any of the patterns above work, please do the above steps to capture the request list anyways!

**Comment by ReporterX** [comment]
Here you are.
![Network Monitor](http://snag.gy/0d9uY.jpg)

I added all in the Allow rules. It does not work.
hktvmall.com>*
d3btqb6knwd3a4.cloudfront.net>*
jwpcdn.net>*

I also tried to add those domains too. It does not work. 
14.198.245.130>*
jwpltx.com>*
scorecardresearch.com>*


You may try to use Zenmate VPN (it's free!) to watch their TV
https://play.google.com/store/apps/details?id=com.zenmate.android&hl=zh_TW
https://itunes.apple.com/us/app/zenmate-for-ios8-best-vpn/id903380113?mt=8

You can choose what location you want to use. Select Hong Kong.

Alternatively, you may use free HK proxies
http://www.xroxy.com/proxy-country-HK.htm

**Comment by alexander255** [comment]
Thank you for pointing me towards ZenMateVPN (it will probably come in handy on some other occasions as well). Also thanks for being so patient with me until me to get this sorted out!

A whitelist update is now available!

Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now :-)

Feel free to close this issue if it works now!

**Comment by ReporterX** [comment]
Yes it works now. What entries did you add? Just these two, right?

```
*.hktvmall.com>*.hktvmall.com
*.hktvmall.com>14.198.2*.*
```

What are the differences between:
```
*.hktvmall.com
*.hktvmall.com>*.hktvmall.com
```

Does `*.hktvmall.com` means `*>*.hktvmall.com` ??

**Comment by alexander255** [comment]
`*.hktvmall.com>*.hktvmall.com` means: Allow everything from any subdomain of `hktvmall.com` (i.e.: `ott-video-lb.hktvmall.com` or `www.hktvmall.com`) to any other subdomain of `hktvmall.com`. This rule allows the page to work even if you are in *Strict* mode (but it does seem to have some influence in non-*Strict* mode as well in some cases?).
Also the reason why `hktvmall.com>*` didn't work (my bad) is because the rule only matches `hktvmall.com`, but none of the subdomains is because it doesn't include subdomains (i.e.: the domain `ott-www.hktvmall.com` isn't included).

`*.hktvmall.com>14.198.2*.*` just allows any subdomain of `hktvmall.com` to access the entire IP range of *Hong Kong Media Production Company Limited* (which is where they host their videos).

The rule `*.hktvmall.com` indeed means the same thing as `*>*.hktvmall.com`. Unfortunately that would be a pretty generic rule (that IMHO is kind of confusing to read) and would also include a lot of stuff that shouldn't be whitelisted (such as the link in this GitHub issue). Since we try to whitelist as little as possible to get pages working I won't be using it a lot.

**Comment by ReporterX** [comment]
Thank you for your explanation.

I've just tested it. `*.hktvmall.com>14.198.2*.*` alone is enough. I haven't encountered a case where I need that rule (`*.hktvmall.com>*.hktvmall.com`) too in non-strict mode. But well it doesn't hurt to keep that rule in the whitelist.

**Comment by alexander255** [comment]
Hi! I've just retested this rule and it appears to no longer be necessary on HKTVMall anymore and will therefor be **removed from the whitelist**.
Please reopen this issue if you experience problems due to this.
