### ISSUE TITLE
White list entries (Google drive and Swiss post)

### ISSUE THREAD

**Issue by neckcen** [meh/smart-referer#33]
drive.google.com>youtube.googleapis.com

Allows videos on google drive to be played.

    *>yellowpay.postfinance.ch
    *>e-payment.postfinance.ch

Prevents "unknown error" with Swiss post's payment system.

**Comment by alexander255** [comment]
Is there a way to away using global wildcards for postfinance? Is it like any website may embed their payment thingy and they then the transaction "mysteriously" fails due to Swiss post not being able to verify the source site's referer?

**Comment by neckcen** [comment]
The way you describe it is correct. Each merchant get attributed an url; when redirected to it, the referer must be the merchant's website or the transaction fails.

However I did some more testing and it appears that sending no referer works fine. The error only happens when in "send page you're going to as referer" mode. So if there is a way to write a rule to send no referer for these domains, then there is no need for wildcards.

**Comment by alexander255** [comment]
Ok, thanks I guess wildcards are unavoidable in this case (No way to change mode for certain URLs atm). :-/

I've added a comment to the whitelist rule so that we can update this rule if this feature ever does become supported.

**Comment by neckcen** [comment]
Cheers! Thanks for the great add-on too :+1:

**Comment by alexander255** [comment]
Your welcome! Thanks for reporting!

PS: Haven't written it, I'm just the whitelist maintainer ;-)

**Comment by alexander255** [comment]
@neckcen: 
This whitelist issue is now almost 3 years old and cannot be reproduced without your help, please retest this issue and give feedback on whether this rule is still required to ensure that whitelist entries are kept up-to-date:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. **Uncheck** the **Use default whitelist** option under **Whitelist Sources**
 5. Remove any custom **Exception** rules that may be related to this issue
 6. Perform the steps required to check whether the documented issue is still reproducible
 7. Re-enabled the default whitelist by performing steps 1 – 4 again checking the **Use default whitelist** option instead

Once you're done with the above steps please leave feedback here so that the whitelist can be updated (either by updating the *Last Checked* date or by removing the rule altogether).
**If you cannot currently perform testing please leave a comment with a rough ETA**, so that we know you're still there. Otherwise, after more than 3 months without any response, the entry will be removed for inactivity.

**Comment by alexander255** [comment]
Also, if you have the time, could you also perform the above steps additionally changing **Rewrite Mode** from **Use the URL you're going to** to **Send nothing, looking like a direct hit**? I'm currently investigating making this the default mode (#113) and your feedback would be very valuable here!
