### ISSUE TITLE
Not display properly on tmall.com

### ISSUE THREAD

**Issue by ReporterX** [meh/smart-referer#34]
(deleted)

It only happens when you set the mode as "send nothing as referer".
I don't think it should be whitelisted in all modes.

**Comment by alexander255** [comment]
Yes, *Smart Referer*'s whitelist targets the non-strict mode, *send URL you're going to* configuration (since it's the most compatible while hardly ever giving a away more data than any of the stricter modes). And since you have indicated that it's huge problem I agree that this can be closed. :-)

Thanks for posting issues for the whitelist after all this time!

**Comment by Gitoffthelawn** [comment]
@alexander255 wrote: "...hardly ever giving a away more data than any of the stricter modes..."

In what case would that setting ever give away more data?

**Comment by alexander255** [comment]
Well, it would be possible that two independent sites run on different sub-domains of the same base domain (i.e.: `a.example.com` and `b.example.com`). If `a.example.com` now includes a resource from `b.example.com` this would result in the URL accessed on `a.example.com` being leaked.
Considering that there are many public services and domain resellers (such as `blogger.com`, `com.au`, `co.uk`, …) that offer these kinds of constellations on large-scale, this may sound kind of worrying. Fortunately most of these are actually on the [public suffix list](https://publicsuffix.org/list/public_suffix_list.dat) and *are* therefor considered to be different domains by browsers and *Smart Referer* (i.e.: `sq-sports.co.uk` is considered to be on a different domain than `guardian.co.uk` for instance). This list was originally created to prevent [supercookies](https://en.wikipedia.org/wiki/Supercookie) and is actively maintained by Mozilla and others to date. As this list is very complete the chances of leaking referers is very small but it *could potentially happen* (hence the "...hardly ever giving a away more data than any of the stricter modes...").

**Comment by Gitoffthelawn** [comment]
@alexander255 Thanks a million for the great explanation.  Also thanks for the details on the PSL.  That's the first time I've heard an explanation of it that actually makes sense and explains its true function.

Regarding your example, I'm a touch confused.  If the extension is set to **send URL you're going to**, and the user is viewing `a.example.com`, which calls a resource from `b.example.com`, wouldn't `b.example.com` just receive it's own URL (`b.example.com/foo`), thereby not leaking anything to `b.example.com`?

**Comment by alexander255** [comment]
No, since both `a.example.com` and `b.example.com` are considered to be on the same domain (= "the same website"). Requests that are considered to be on the same domain will just be sent the referer header as usual.
For example:
If I click on the "Code" button (on the top of the right navigation bar) on this page then my browser navigates to `https://github.com/meh/smart-referer` with a referer of `https://github.com/meh/smart-referer/issues/34` being sent. If I click on the *public suffix list*-link above, on the other hand, then the target page (`https://publicsuffix.org/list/public_suffix_list.dat`) receives its own URL (`https://publicsuffix.org/list/public_suffix_list.dat`) as the referer (since it's on a different domain).

**Comment by Gitoffthelawn** [comment]
Got it.  Thank you for clarifying.

Your writing style is very clear and effective.  That is a rare ability.  You would be successful as a technical writer as well!  :-)

**Comment by alexander255** [comment]
Thanks! I don't usually get complements for writing explanations. :-)

You're very welcome for the explanation! :-)
