### ISSUE TITLE
pokelocate.io - can't display images

### ISSUE THREAD

**Issue by ReporterX** [meh/smart-referer#39]
https://pokelocate.io/

All Pokemon images can't be shown.

**Comment by alexander255** [comment]
Apparently S3 offers a [policy matcher for HTTP Referers](http://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html#example-bucket-policies-use-case-4) that will block everything that does not match the given Referer URL (including empty Referers).
If this becomes more widely used, it might severely limit the utility of SmartReferer as a whole. :disappointed:

**Comment by alexander255** [comment]
This site should be fixed now, but if more AWS sites start doing this, then this problem might become big… :unamused: 

Anyways, thanks for reporting an please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now :-)

Feel free to close this issue if it works now!

**Comment by ReporterX** [comment]
Yes it is working now. Thank you. 

Perhaps we could add this exception if it becomes more widely used.
`*>s3.amazonaws.com`
What do you think?

**Comment by Gitoffthelawn** [comment]
It is useful for people to ask web developers to turn off referrer checking.  Since it is so easily spoofed, it is meaningless for developers to use.

**Comment by alexander255** [comment]
@ReporterX: My thoughts on that:

 * Con:
   - Making referer tracking by 3rd-party services harder is IMHO the whole point of this add-on, so we should try not to "privilege" any services by whitelisting them as a whole
   - The fewer exceptions (for different sites), the better
 * Pro:
   - Resources shipped from `amazonaws.com` are almost always integral parts of the website currently visited (so `amazonaws.com` could be considered part of each of the individual web sites)

In the end it will be decided by web developers themselves and *Smart Referer* will just have to follow their lead, whichever way they decide.

@Gitoffthelawn: As a security feature the referer is indeed a very bad thing to use, but for preventing unwanted co-developers from embedding your stuff on their page it works reasonably well. If developers would unconditionally allow same-domain and empty referer requests for their resources, *Smart Referer* would never cause any issues *ever* and wouldn't need the whitelist.
Most developers won't care about same-domain and empty referer requests either way, so asking them for this probably has a much higher chance of success.

Maybe we could just convince Amazon to always allow their stuff to be used by servers of their own domain?

**Comment by meh** [comment]
From a privacy point of view I think CDNs getting the referer wouldn't be a problem, since they already know where they're being used from.

If all it does is check the domain matches then a good solution could be to have a separate white list for CDNs that instead of sending the intact referer clamps it to only contain the domain.

Can someone confirm sending just the domain works in this case? If so I'll add the feature (unless someone has arguments against what I said above about privacy).

**Comment by Gitoffthelawn** [comment]
@alexander255 I agree completely with your pros and cons.  Great analysis.

Too often, developers succumb to only honoring the pro without honoring the cons.  If everything gives in to questionable practices, they become the norm.

**Comment by Gitoffthelawn** [comment]
@meh I think a little lobbying of Amazon to change their practices may be in order.

That said, your idea is a good one if they refuse to yield.  Just remember to design it to always pass the very bare minimum required.

**Comment by alexander255** [comment]
`pokelocate.io` is no longer available, therefor its whitelist rule be removed.

**Comment by Gitoffthelawn** [comment]
A while back, our friend @alexander255 wrote:
> As a security feature the referer is indeed a very bad thing to use, but for preventing unwanted co-developers from embedding your stuff on their page it works reasonably well.

In rereading this just now, it made me wonder: If a co-developer really wanted to embed unauthorized content, could they programmatically set the referer to spoof it?

**Comment by alexander255** [comment]
Not that I know of, no. Referer is bad for security-related stuff because there is no guarantee that it will indeed contain what is generally considered to be "the previous page". Some proxies are known to obfuscate or discard that header; loading websites in iframes or using meta-refresh can have unexpected effects as well, etc. Better to use things like security tokens to check that the user indeed came from the correct login form.

OTOH: If you want to embed an image from somebody who does not like you, you generally aren't satisfied with finding one weird way to get that image to load under most circumstances. You want the image to *always* load for *every* user – and that is afaik impossible with the current referer system. Hence why it works (well) for that kind of usage.

**Comment by Gitoffthelawn** [comment]
@alexander255 Thank you for your analysis!
