### ISSUE TITLE
Website redirection

### ISSUE THREAD

**Issue by SMed79** [meh/smart-referer#40]
Hi, 
**smart referer 0.0.11.1** even if you whitelist the site `streamcomplet.com`, any page **redirect** you to the home page (no issue when disabled).

Thank you.

**Comment by alexander255** [comment]
Thanks for your report!

It turns out the sites video hosting network (`media.vimple.me`) uses referers to determine whether a page access is legit or not, when the referer check fails the player will fail to load which will (for strange reasons) cause the main site to redirect to the homepage.
BTW: Whitelisting `streamcomplet.com>*` instead of `streamcomplet.com` would have worked around the issue as well.

Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now :-)

Feel free to close this issue if it works now!

**Comment by SMed79** [comment]
I confirm that it works.
Thanks you :smile:
