### ISSUE TITLE
bing.com - cannot log into Microsoft account

### ISSUE THREAD

**Issue by mcbarky** [meh/smart-referer#41]
Unable to log into Microsoft account via `bing.com`

Whitelist solution: `*.live.com>*`

**Comment by alexander255** [comment]
Thanks for reporting this issue!

I've opted for whitelisting all of `login.live.com>*` since any service using the *Windows Live* SSO could be affected as well.

Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now :-)

Feel free to close this issue if it works now!

**Comment by mcbarky** [comment]
Confirmed fixed, thanks!

**Comment by alexander255** [comment]
@mcbarky: This whitelist issue is now over 2 years old and cannot be reproduced without your help, please retest this issue and give feedback on whether this rule is still required to ensure that whitelist entries are kept up-to-date:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. **Uncheck** the **Use default whitelist** option under **Whitelist Sources**
 5. Remove any custom **Exception** rules that may be related to this issue
 6. Perform the steps required to check whether the documented issue is still reproducible
 7. Re-enabled the default whitelist by performing steps 1 – 4 again checking the **Use default whitelist** option instead

Once you're done with the above steps please leave feedback here so that the whitelist can be updated (either by updating the *Last Checked* date or by removing the rule altogether).
**If you cannot currently perform testing please leave a comment with a rough ETA**, so that we know you're still there. Otherwise, after more than 3 months without any response, the entry will be removed for inactivity.

**Comment by alexander255** [comment]
Also, if you have the time could you also perform the above steps additionally changing **Rewrite Mode** from **Use the URL you're going to** to **Send nothing, looking like a direct hit**? I'm currently investigating making this the default mode (#113) and your feedback would be very valuable here!
