### ISSUE TITLE
Smart Referer stoped working

### ISSUE THREAD

**Issue by SMed79** [meh/smart-referer#43]
Hi, 

since a few days **Smart Referer** seem to be not working in new profile.

could you please check `https://www.whatismyreferer.com/`

Arch Linux
Firefox 49.0.2 
Smart Referer 0.0.11.1-signed.1-signed

(also tested in Win7 + FF portable)

Thank you.

**Comment by alexander255** [comment]
Thank you for reporting this. Apparently this was caused by a malformed entry in the default whitelist (yes that means it was my fault!).
I've fixed the rule in commit 66ceba5a22a5d72a3ca08c36e4dfd8996916aa16 and opened PR #44 so that whitelist entries will be properly sanitized from now on to prevent such disaster from happening ever again.

**Comment by alexander255** [comment]
Please reload the add-on and check weather this is fixed for now.

**Comment by SMed79** [comment]
Seem to be working now. Thank you.

**Comment by alexander255** [comment]
Thanks for the feedback. Long term fix will be discussed in #44.
