### ISSUE TITLE
Issues with whitelist

### ISSUE THREAD

**Issue by kirill9000** [meh/smart-referer#55]
I assume that Smart Referer is a tool for privacy-minded advanced users. Why then does it contain whitelist, that is not only enabled by default, but also served from author's personal domain and via HTTP? Please consider making it opt-in instead of opt-out and moving it to GitHub. Thank you.

**Comment by meh** [comment]
It is on GitHub, I contacted them back when I introduced whitelists to ask which was the best way to provide it without getting banned.

They said to put it on the GitHub page for the project, and [it is](https://github.com/meh/smart-referer/tree/gh-pages) but I also use GitHub pages for my own website, so it goes through the CNAME.

If you don't like it just make the field blank, or host your own whitelist. Normal users will care more about websites not working with the addon than the fact the whitelist is external.

**Comment by kirill9000** [comment]
>and it is

Then why don't you serve it via GitHub domain and through HTTPS?

>If you don't like it just make the field blank, or host your own whitelist.

Thanks for the tip, I would never have thought of that myself. But issue is not about what I like or don't like. It's about whether this extensions aims to improve privacy or not.

 >Normal users will care

Normal users don't know what referer is and certainly don't care.

**Comment by meh** [comment]
>Then why don't you serve it via GitHub domain

Did you skip the part about the CNAME?

If you use `http://meh.github.io/smart-referer/whitelist.txt` it will go to `http://meh.schizofreni.co/smart-referer/whitelist.txt`.

> and through HTTPS?

GitHub pages do not support HTTPS.

**Comment by kirill9000** [comment]
>GitHub pages do not support HTTPS.

Why don't you just put it into a normal repository then like, for example, uBlock does with it's assets?

>I made the extension for myself

Since you don't use self-signed version, but had gone through all the trouble of getting through AMO review process, I assume you want to help other people too.

>I had also been contacted by one of those companies trying to put ads and tracking into Firefox extensions and blogged about it when it happened.

Don't take it personally, I'm not accusing you of anything. I just don't think this addon needs that feature enabled by default.

>If it's just "it doesn't feel right", well, that's on you.

So your decision to not make whitelist opt-in instead of opt-out is final?

**Comment by meh** [comment]
>Why don't you just put it into a normal repository then like, for example, uBlock does with it's assets?

Because GitHub doesn't like you abusing actual repositories for that since they don't have as much caching as they do for GitHub pages, uBlock might have been in contact with them and got an exception, I do not know that, I just know the response they gave me when they asked, and it was to use pages, so that's what I do.

>Since you don't use self-signed version, but had gone through all the trouble of getting through AMO review process, I assume you want to help other people too.

If that's what happens then it's good, but it's a pain to use self-signed versions when you have more than one machine, so having it on AMO was better than not.

>Don't take it personally, I'm not accusing you of anything. I just don't think this addon needs that feature enabled by default.
>
>So your decision to not make whitelist opt-in instead of opt-out is final?

It's easier to tell people to make the whitelist URL blank and intentionally opt-in to websites not working anymore than to tell people to add a specific URL if known websites with whitelist workarounds stop working.

All of this is also mentioned in the README.

**Comment by alexander255** [comment]
@meh Couldn't you set it up to use a URL like this: https://meh.github.io/smart-referer/whitelist.txt

**Comment by meh** [comment]
@alexander255 I remember trying back when I introduced it, and it wasn't working in the extension. But even if I did that and it worked, if anyone actually visited that URL they'd end up on `meh.schizofreni.co` anyway because of the CNAME configuration and the same question would pop up again.

I understand the issue with having the whitelist on a seemingly random domain and without HTTPS, but people can verify it's actually going where it claims to be going and if someone is MITMing you having a whitelist for referers modified is the last of your problems.

**Comment by alexander255** [comment]
Hmm… I have never used GitHub pages and I probably never will, so I'll ask: Is it not possible to assign smart-referer to a different domain than your personal web site? Maybe moving smart-referer to a group would allow for that?
I can see how moving `meh.github.io` to HTTPS would break `meh.schizofreni.co` because the certificate isn't valid for that domain, through. :slightly_frowning_face:

**Comment by scribblemaniac** [comment]
Github Pages does indeed [support HTTPS now](https://github.com/blog/2186-https-for-github-pages), and it can even [be forced](https://help.github.com/articles/securing-your-github-pages-site-with-https/), so I think it would be beneficial to move to it if possible. If you want to leave your CNAME as is, you can create a organization (for free), and move this repository to the organization. That should provide a completely separate Github Pages domain that will be unaffected by your record.

**Comment by alexander255** [comment]
@meh: Please close this again if you think that the change to put the project on a separate organization is not doable/reasonable for some reason, otherwise I'd like to include this in the upcoming 0.2.1 release if possible (#54).

**Comment by meh** [comment]
Someone ping me againby  the next weekend if I forget about this.

**Comment by alexander255** [comment]
@meh This is your belated ping since it looks like we all forgot about this for a while. 😁

**Comment by alexander255** [comment]
Any progress on this? It would be nice if we could get this over with soonish…

**Comment by alexander255** [comment]
@meh It's now 2 months later and, well, there hasn't been any response from you in a while…
Could you maybe update us on the current status of this?

**Comment by Gitoffthelawn** [comment]
@alexander255 Can you help decipher the format of the whitelist?  Here is the current default whitelist:

     *.disqus.com disqus.com api.solvemedia.com *.github.com>*.github.com github.com>*.github.com *.github.com>github.com typekit.com *.typekit.com typekit.net *.typekit.net *.baidu.com>*.bdimg.com baidu.com>*.bdimg.com *.dm5.com>*.cdndm5.com dm5.com>*.cdndm5.com drive.google.com>youtube.googleapis.com login.live.com>* *>*.postfinance.ch streamcomplet.com>media.vimple.me *.sofort.com *.sofortueberweisung.de *>cloud.typography.com videoweed.es>*.coolcdn.ch *.videoweed.es>*.coolcdn.ch novamov.com>*.coolcdn.ch *.novamov.com>*.coolcdn.ch *>*.vivocha.com *>vivocha.com

**Comment by alexander255** [comment]
@Gitoffthelawn: You probably want to look at the full (non-minimized) version of the whitelist instead:
http://meh.schizofreni.co/smart-referer/whitelist.full.txt

The format is *source host*>*target host* (where both sides may contain wildcard characters: `*` & `?`).  After a hash character (`#`) the remainder of the line is ignored.

**Comment by Gitoffthelawn** [comment]
@alexander255 Thank you!  That makes much more sense now!

BTW, I've been using GitHub w/o any referers, and I haven't found any issues.  Not sure if there is any need for it in the whitelist.  Of course, it wouldn't surprise me if there is a case I have yet to test.

**Comment by kirill9000** [comment]
@meh 
@alexander255 
Since AMO now has automated reviews and new versions of addons can be rolled out in a matter of minutes, how about making the whitelist built-in?

**Comment by kirill9000** [comment]
@meh
@alexander255
bump

**Comment by alexander255** [comment]
@kirill9000: I'm not opposed to it, but it does mean that we cannot just merge PRs like #80 and be done with it. Considering that we're both not terribly active at maintaining this currently, this adds some extra effort that I at least don't really want to have. I simply won't bother going through the extra steps of pulling the whitelist, assembling a release and pushing it. Having a bot for this would likely change my mind through.

**Comment by alexander255** [comment]
Anyways the HTTPS issue has been solved by using https://raw.githubusercontent.com/meh/smart-referer/gh-pages/whitelist.txt for the default whitelist. In the unlikely case that somebody is willing to write that bot I'd be willing to make the default whitelist built-in, otherwise things will stay as-is.
