### ISSUE TITLE
Settings disappeared

### ISSUE THREAD

**Issue by tingeltangelbob4u** [meh/smart-referer#56]
I just discovered a world ball in my Firefox status bar, that says Smart Referer when I hover over it, but when I click nothing is happening. When I look to my addons and click on Smart Referer the settings disappeared. Is this addon still working? Where have the settings gone?

**Comment by alexander255** [comment]
Hi! Thanks for reporting this issue with *Smart Referer*!
Recently Mozilla has *finally* approved the almost-rewrite 0.2 version of the add-on with compatibility for Firefox 57+, so some issues can't be avoided, I guess. :slightly_smiling_face: Sorry for any inconvenience either way!

Please answer the following questions so that we can help you:

 * Could you please state your browser and operating system name and version?
 * With "the settings have disappeared" you mean that clicking on *Extensions* → *Smart Referer* → *Settings* only displays the extensions name and description, but no settings?
    * If yes, does that behaviour persist if you refresh that tab?
 * Does the "world ball" turn pale when you click on it?
 * Are there any errors in the error console (Ctrl+Shift+J) displayed when you disable and re-enable *Smart Referer*?
    * If yes, please provide a screenshot of the error message or copy-paste it into your response.

Please provide as much information as you can, the more we have the better we'll be able to help you. :grin:

**Comment by tingeltangelbob4u** [comment]
Hi and thanks for your answer. I am using Firefox 54.0.1 on Windows 7.

Since I restarted my browser the world ball disappeared, and now there is an empty space in my status bar. But I still can hover over the empty space and the words "Smart Referer" appear and a little square. When I click the square it turns pale but nothing else is happening.

When I click on Extensions / Smart Referer there are still no settings. But when I deactivate and then reactivate the addon the settings suddenly appear. Though when I restart Firefox, the settings are gone again.

This is what I can find in the error console:

CustomizableUI:unable to normalize widget  CustomizableUI.jsm:2141

Warning: attempting to write 5717 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Warning: attempting to write 4161 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
CustomizableUI:unable to normalize widget  CustomizableUI.jsm:2141
Warning: attempting to write 5716 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
aId is undefined  CustomizableUI.jsm:1230
[Exception... "Component returned failure code: 0x805e0006 [nsIWebNavigation.loadURIWithOptions]"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: chrome://global/content/bindings/browser.xml :: loadURIWithFlags/< :: line 156"  data: no]

**Comment by alexander255** [comment]
Is this still an issue with recent (57+) Firefox, because if it is this should probably be reported to Mozilla.

**Comment by alexander255** [comment]
Closing for no response.
