### ISSUE TITLE
Issues on Android

### ISSUE THREAD

**Issue by githubnin** [meh/smart-referer#60]
There are problems with version 0.2 on Android 6.0.1 with Firefox 55.0.2. The add-on installs but its settings are not displayed anywhere and therefore cannot be reviewed or changed without going through about:config. The add-on installed an entry into the browser's menu (3 verticle dots) but it does nothing when selected. However the addon appears to be functioning properly.

**Comment by alexander255** [comment]
Yeah, I temporarily suspended FireFox for Android development until they got around to fixing to the most anoying limitations of their WebExtension implementation of that platform.

Specifically I waited for the following issues to be addressed:

  * ~[1302504](https://bugzilla.mozilla.org/show_bug.cgi?id=1302504)~ (Support for `options_ui` / “settings not displayed anywhere” – fixed in 56.0.0)
  * ~[1367494](https://bugzilla.mozilla.org/show_bug.cgi?id=1367494)~ (Don't display add-ons as "broken" that use manifest keys unknown to the browser – fixed in 55.0.2)
  * ~[1351111](https://bugzilla.mozilla.org/show_bug.cgi?id=1351111)~ (Minimal support for `browser_action`s aka “menu entries” – fixed in 55.0.0)

As that is now (finally!) the case, the next version (2.0.1, currently proposed in #54) has been updated to work correctly with minimal `browser_action` support available on FireFox for Android 55.0.2+. It also contains a mobile-friendly options UI that will only become visible in FireFox for Android 56.0.0+ through.

The core functionally of the extension has never been affected by these UI issues, as correctly noticed. Expect an update – fixing the remaining issues – soon (no :tm: 😉).

**Comment by githubnin** [comment]
Thank you. I look forward to the update. Extensions are auto-updated by default in Firefox for Android so it messed things up a bit when 0.0.11.1 was updated to 0.2.

**Comment by alexander255** [comment]
The fix has been uploaded to AMO and should be reviewed within the next week.
If you had any custom settings in the bootstrapped version of the extension, then they will have been automatically migrated and enabled to the WebExtension (i.e.: You're using them right now.) – you just won't be able to view and/or edit them until you update to FireFox for Android 56.

Thanks for putting this on my radar again! :+1:
