### ISSUE TITLE
Add ability to set certain sites to always be given a specific referer

### ISSUE THREAD

**Issue by vertigo220** [meh/smart-referer#87]
For example, it could be set to always tell WSJ the referer is Google, which would allow it to take over the functionality provided by add-ons like Bypass Paywalls. In fact, until I realized the cause, I was often having content blocked from me due to this even if I _was_ coming from google, since I use header spoofing.

**Comment by Joel889** [comment]
This is my number 1 request for this addon, switching from the now defunct refcontrol:
https://addons.mozilla.org/en-US/firefox/addon/refcontrol/

Spoofing features for individual domains could be:
Normal (no spoofing), block, custom URL, root target host, root referrer host.

Also, the same selections as above could be made available as default action choices for domains not listed.

Thank you

**Comment by alexander255** [comment]
@Joel889: Could you take a look at my other add-on, [User-Agent Switcher](https://addons.mozilla.org/de/firefox/addon/uaswitcher/), and see if the UI (roughly) matches your expectations? (Just mentally substitute all occurances of stuff related to *User-Agent*s with *Referer*s.)
I'm asking you this because it looks like there is a lot of overlap between what you're outlining here and what I've implemented for that other extension. Any feedback welcome!

**Comment by Joel889** [comment]
Yes, that looks like great.

**Comment by ntninja** [comment]
This issue has been moved to GitLab: https://gitlab.com/smart-referer/smart-referer/issues/87
