### ISSUE TITLE
Browser Console Spam

### ISSUE THREAD

**Issue by GitCurious** [meh/smart-referer#91]
When right clicking on the toolbar icon and choosing "Preferences"

I see the browser console fill with many messages - I have pasted them here:
https://pastebin.com/wq2g9M48

This only seems to happen once per browser session, then does not happen again until after a browser restart.

Firefox 60
Waterfox 56.2

**Comment by alexander255** [comment]
Thank you for reporting this. There is no actual error here however and this won't be “fixed”. See the detailed analysis below.

These errors appear when you, for the first time since the extensions was started (browser startup, updates, disable/enable), open some UI that loads translations. We use a library named `l10n.js` that populates the text on all UI elements in the current UI language using the extension's message catalog. Unfortunately, as per the documentation of the [`browser.i18n.getMessage`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n/getMessage) function used for this:

> If the message can't be found in messages.json:
>
> * Firefox returns "" and logs an error. (← This is what you see in the console!)
> * Chrome returns "" and does not log an error.

There is also no way to suppress this error or check beforehand whether the request message ID exists. Hence all possible IDs are queried for anyway and Firefox will log (useless) errors because of this.

There is nothing we can do about this (other than using a less-convinient translation support library), nor do I at least care
