### ISSUE TITLE
Google Drive - downloading multiple files fails

### ISSUE THREAD

**Issue by vertigo220** [meh/smart-referer#97]
When trying to download a group of files, it gives an error saying "zip failed." To fix this, you need to add drive.google.com > takeout*.google.com. Don't miss the *, since it appends more (what I'm assuming is random) data there. I suggest adding this to the whitelist.

**Comment by alexander255** [comment]
Thanks for reporting this! I've added this to the whitelist now.
Please test to make sure it works as expected:

 1. Open the **Add-ons** page from the menu button on the toolbar
 2. Select the entry named **Extensions** from the left-hand side of the add-on page
 3. Click on the **Settings** button beneath **Smart Referer** in the extension list
 4. Make sure you use the default **Whitelist Source** (`http://meh.github.io/smart-referer/whitelist.txt`)
 5. Remove any custom **Allow** rules that are related to this bug
 6. Click on the **Disable** button towards to bottom of *Smart Referer*'s extension page
 7. Wait for *Smart Referer* to be disabled then click the *Enable* to re-enable button (this will force a whitelist update)
 8. Check if your page is working now 🙂 

Feel free to close this issue if it works now!

**Comment by alexander255** [comment]
Do you have any experience programming, btw? Because I very much doubt that I'll even seriously consider adding half the features you asked for in recent months because, at least for me, *Smart Referer* is pretty much feature-complete. (I'm of course open for doing paid work if you're interested…) Just telling ya' that all enhancements marked as „Priority: Low“ are pretty unlikely to be addressed by me like *ever*. 😉

**Comment by vertigo220** [comment]
Appears to work, as expected. :)

I only have very limited experience, with basic, batch files, HTML, LUA, VB, and bash/dash, but nothing "serious" like JS or C, so I highly doubt I would be able to do it. I understand that you only have so much time and can only do what you can, and even without my suggestions it's still a great add-on. I just throw out ideas I'd like to see implemented and if they happen great, if not, just how it is. And who knows, maybe someone who does have the knowledge to do it will come along and think one is a good idea and write the code for it.

**Comment by alexander255** [comment]
JS is not really what I'd classify as a „serious“ language: It's designed to be quite easy for beginners and to quickly get *something* working. 🙂 
(When you get more advanced, it will get somewhat annoying and hard to maintain through, so many developers use TypeScript instead and transpile that to JavaScript later on.)

If you're interested in helping out a bit, I'd recommend [*Add ability to export/import settings*](https://github.com/meh/smart-referer/issues/86) as an „absolute beginner“-friendly issue since it requires very little knowledge of both JavaScript and the current codebase – I'd be happy to mentor you on this one as well. (You don't have to say, I'm just putting the possibility out there.)

**Comment by alexander255** [comment]
@vertigo220: Sorry I haven't responded for so long. If you're still interested in this I guess we should start it slowly then.

At this point we can mostly ignore GIT however: The only commands you'll likely need are `git clone` (take a full copy of some other repository), `git add` (add files to “stage” for commiting), `git commit` (create/update a bunch of changes) & `git push` (copy commits to some other repository).

 * As a very basic tutorial of how to use GIT, I'd recommend this: https://rogerdudler.github.io/git-guide/ (Translated into 15 languages with links on how to install.)
 * There is also the a bit more advanced official GIT tutorial available as `man 7 gittutorial` or at: https://git-scm.com/docs/gittutorial (The other linked tutorial should do for our purposes however.)

In order to create a usable GIT offline copy of this repository:

  1. Log into GitHub
  2. Click the “Fork” button near the top of this page (this will create a copy of this repository for you to edit)
  3. Click the “Clone or Download” button and copy the displayed URL (should look like this: `git@github.com:vertigo220/smart-referer.git`)
  4. Run `git clone <copied-url>` to download the repository into the current directory

Before you try to do any work on *Smart Referer* however I'd highly recommend following the “Getting Started” guide on Mozilla's [WebExtensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) developer page.
After doing this we can investigate how you can best learn to necessary skills required to contribute to this project. Is there anything you would particularily like to work on?
Feel free to contact me here or via e-mail if you need help with anything :slightly_smiling_face:
